apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  labels:
    app: node-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        image: izakdvlpr/node-express-api:v8
        envFrom:
        - configMapRef:
            name: node-server-env
        volumeMounts:
        - mountPath: "/usr/src/app/myfamily"
          name: config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: node-server-family
          items:
          - key: members
            path: "family.txt"
