apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  labels:
    app: node-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        image: izakdvlpr/node-express-api:v9.3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
          failureThreshold: 1
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
          successThreshold: 1
          initialDelaySeconds: 15
        envFrom:
        - configMapRef:
            name: node-server-env
        - secretRef:
            name: node-server-secret
        volumeMounts:
        - mountPath: "/usr/src/app/myfamily"
          name: config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: node-server-family
          items:
          - key: members
            path: "family.txt"
