apiVersion: v1
kind: Service
metadata:
  name: node-server-service
  namespace: default
spec:
  selector:
    app: node-server
  type: ClusterIP
  ports:
  - name: node-server-service
    port: 80 # porta do service
    targetPort: 8000 # porta do container
    protocol: TCP
