apiVersion: v1
kind: Service
metadata:
  name: node-server-service
  namespace: default
spec:
  selector:
    app: node-server
  type: ClusterIP
  ports:
  - name: node-server-service
    port: 3333
    protocol: TCP
